#!/usr/bin/env bash
set -euo pipefail

# Refreshes the vendored IntelliJ Platform SDK reference in the context corpus.
#
# Source of truth is the OFFICIAL llms.txt the JetBrains docs site publishes
# (generated by Writerside with <llms-txt/> — includes and variables already
# resolved). No Docker, no Writerside builder, no local IDE needed.
#
# Steps:
#   1. download the current llms.txt into the gitignored workspace
#   2. run the pure-Kotlin converter, which slices it into the narrow-core
#      topics and writes corpus/generated/sdk-platform/<slug>.md
#
# Commit the resulting corpus/generated/sdk-platform/ changes. `./gradlew build`
# then packs them into the plugin jar under context-corpus/.

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WORKSPACE="$ROOT/.writerside-build"
LLMS_URL="https://plugins.jetbrains.com/docs/intellij/llms.txt"

mkdir -p "$WORKSPACE"
echo "Downloading $LLMS_URL"
curl -fsSL -o "$WORKSPACE/llms.txt" -D "$WORKSPACE/llms.headers.txt" "$LLMS_URL"
grep -i '^last-modified:' "$WORKSPACE/llms.headers.txt" || true

"$ROOT/gradlew" convertSdkDocs

echo "Done. Review and commit corpus/generated/sdk-platform/."
