package com.github.xepozz.ide.introspector.context

object SdkDocsNarrowCore {
    val TITLES: Set<String> = linkedSetOf(
        "Plugin Structure",
        "Plugin Content",
        "Plugin Configuration File",
        "Extensions",
        "Extension Points",
        "Services",
        "Listeners",
        "Disposer and Disposable",
        "Messaging Infrastructure",
        "Threading Model",
        "Kotlin Coroutines",
        "Coroutine Scopes",
        "Coroutine Dispatchers",
        "Launching Coroutines",
        "Coroutine Read Actions",
        "Coroutines on EDT and Locks",
        "Coroutine Tips and Tricks",
        "Coroutine Dumps",
        "Background Processes",
        "Persistence Model",
        "Persisting State of Components",
        "Persistent State Component in Split Mode",
        "Persisting Sensitive Data",
        "Settings",
        "Settings Guide",
        "Custom Settings Groups",
        "Virtual File System",
        "Virtual Files",
        "Action System",
        "Tool Windows",
        "Notification Balloons",
        "Run Configurations",
        "Program Structure Interface (PSI)",
        "PSI Files",
        "PSI Elements",
        "Navigating the PSI",
        "PSI References",
        "Modifying the PSI",
        "PSI Cookbook",
        "PSI Performance",
        "Indexing and PSI Stubs",
        "Intentions",
        "Code Inspections",
        "Inspection Options",
    )
}
